name: Publish

on:
  release:
    types: [published, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}
      - run: npm ci
      - run: npm run build
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          commit_message: |
            Automatic build
            Commit ${{github.sha}}
            Run ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
